# Generated by Django 5.1.5 on 2025-02-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_category',
        ),
    ]
