# Generated by Django 5.1.5 on 2025-04-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button',
            field=models.BooleanField(default=False),
        ),
    ]
