# Generated by Django 5.1.5 on 2025-05-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_invoice_invoiceitem_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Error', 'Error')], max_length=20),
        ),
    ]
