# Generated by Django 5.1.5 on 2025-05-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Error', 'Error')], default='Pending', max_length=20),
        ),
    ]
